const travelData = {
    products: [
        {
            name: 'Visit Barcelona',
            slug: 'visit-barcelona',
            category: 'city',
            image: '/images/barcelona.jpg',
            price: 600,
            offer: 'Trip to Barcelona of 6 days.' ,
            including: 'Accommodation in Sagrada Familia, Return flight with Vueling company, Tickets to : Camp Nou stadium, National Art Museum of Catalonia (MNAC),Picasso Museum, Barcelona Cathedral, Casa Milà "La Pedrera", Basilica of La Sagrada Familia, Casa Batlló, Palau de la Música Catalana Auditorium',
            description: 'Barcelona is a city with a wide range of original leisure options that encourage you to visit time and time again. Overlooking the Mediterranean Sea, and famous for Gaudí and other Art Nouveau architecture, Barcelona is one of Europe’s trendiest cities. It’s a hub of new trends in the world of culture, fashion and cuisine. It combines the creativity of its artists and designers with respect and care for local traditions. The charm and slower pace of the old town, the avant-garde vibe of more modern neighbourhoods, and the fast pace of one of the world’s most visited cities coexist in Barcelona...',
          },
          {
            name: 'Experience Lisabon',
            slug: 'lisabon',
            category: 'city',
            image: '/images/lisabon.jpg',
            price: 740,
            offer: 'Trip to Lisabon of 7 days.' ,
            including: 'Accommodation in famous hotel, Return flight, Ticket to Torre de Belem,Day trip to Sintra, Cascais, Visit to Rossio Square, Church of Sao Roque and Ribeira Market',
            description: 'Lisbon, Portuguese Lisboa, city, port, capital of Portugal, and the centre of the Lisbon metropolitan area. Located in western Portugal on the estuary of the Tagus (Tejo) River, it is the westernmost capital city in continental Europe and serves as the country’s chief port, largest city, and commercial, political, and tourist centre.Lisbon is one of Europe’s best value cities. You can find beautiful accommodation in stylish apartments and guesthouses from around €20 per night and get change from a €5 note for a quick breakfast, sandwich lunch or cheeky sun-downer  at one of the open-air kiosks ',
          },
          {
            name: 'Berlin with us',
            slug: 'berlin',
            category: 'city',
            image: '/images/berlin.jpg',
            price: 540,
            offer: 'Trip to Berlin of 6 days.' ,
            including: 'Accommodation in famous hotel, Return flight, Ticket to Stroll through Brandenburg Gate,Visit the glass dome of The Reichstag,Experience the glorious Berlin Cathedral',
            description: 'Berlin, capital and chief urban centre of Germany. The city lies at the heart of the North German Plain, athwart an east-west commercial and geographic axis that helped make it the capital of the kingdom of Prussia and then, from 1871, of a unified Germany. Berlin’s former glory ended in 1945, but the city survived the destruction of World War II. It was rebuilt and came to show amazing economic and cultural growth.Berlin is situated about 112 miles (180 km) south of the Baltic Sea, 118 miles (190 km) north of the Czech-German border, 110 miles (177 km) east of the former inner-German border, and 55 miles (89 km) west of Poland. It lies in the wide glacial valley of the Spree River, which runs through the centre of the city.',
          },
          {
            name: 'Paris and carpe diem',
            slug: 'paris',
            category: 'city',
            image: '/images/paris.jpg',
            price: 740,
            offer: 'Trip to Paris of 5 days.' ,
            including: 'Accommodation in famous hotel, Return flight, Ticket to Musée du Louvre, Eiffel Tower, Jardin des Tuileries, Sacred Heart Basilica of Montmartre, Pere-Lachaise Cemetery (Cimetiere du Pere-Lachaise)',
            description: 'Paris, city and capital of France, situated in the north-central part of the country. People were living on the site of the present-day city, located along the Seine River some 233 miles (375 km) upstream from the river’s mouth on the English Channel (La Manche), by about 7600 BCE. The modern city has spread from the island (the Île de la Cité) and far beyond both banks of the Seine. Paris occupies a central position in the rich agricultural region known as the Paris Basin, and it constitutes one of eight départements of the Île-de-France administrative region. It is by far the country’s most important centre of commerce and culture. Area city, 41 square miles ',
          },
          {
            name: 'Experience Budapest',
            slug: 'budimpesta',
            category: 'city',
            image: '/images/budimpesta.jpg',
            price: 240,
            offer: 'Trip to Budapest of 5 days.' ,
            including: 'Accommodation in famous hotel, Return flight, Ticket to Parliament Building, Gellért Baths,Heroes’ Square,Margaret Island,Danube Promenade,House of Terror',
            description: 'Budapest offers a number of historical buildings, baths and parks and is considered a financial hub.In the city center, we can find the Roman Catholic cathedral, the St. Stephens Basilica. The church is a Neo-Renaissance-style cathedral in the 5th district of Budapest. It is one of the most significant church buildings in Hungary. The building is named in honor of the Hungarian founding king, St. Stephen (975-1038), whose right hand, the Holy Right, is kept here as a relic. With a height of 96 meters, it is the fourth-tallest building in the country and the third tallest in the capital after the Parliament and the MOL Campus.  It was the sixth-largest church building in Hungary before 1920. The former royal palace, the Buda Castle -as part of the Castle District- has been part of Budapests World Heritage Sites since 1987. ',
          },
          {
            name: 'Visit London',
            slug: 'london',
            category: 'city',
            image: '/images/london.jpg',
            price: 550,
            offer: 'Trip to London of 6 days.' ,
            including: 'Accommodation in famous hotel, Return flight, Ticket to  Hyde Park, Westminster,London Eye, Shoreditch,Hampstead Heath,Thames Cruise, Brixton Academy',
            description: 'London, city, capital of the United Kingdom. It is among the oldest of the world’s great cities—its history spanning nearly two millennia—and one of the most cosmopolitan. By far Britain’s largest metropolis, it is also the country’s economic, transportation, and cultural centre.London is situated in southeastern England, lying astride the River Thames some 50 miles (80 km) upstream from its estuary on the North Sea. In satellite photographs the metropolis can be seen to sit compactly in a Green Belt of open land, with its principal ring highway (the M25 motorway) threaded around it at a radius of about 20 miles (30 km) from the city centre. ',
          },
          {
            name: 'Shop in Milano',
            slug: 'lisabon',
            category: 'city',
            image: '/images/milano.jpg',
            price: 340,
            offer: 'Trip to Milano of 5 days.' ,
            including: 'Accommodation in famous hotel, Return flight, Ticket to Milan Cathedral, La Galleria Vittorio Emanuele II,La Scala de Milan,Parco Sempione, Santa Maria delle Grazie church',
            description: 'Milan, Italian Milano, city, capital of Milano province (provincia) and of the region (regione) of Lombardy (Lombardia), northern Italy. It is the leading financial centre and the most prosperous manufacturing and commercial city of Italy.The destiny of Milan, like that of many of the world’s great cities, remains something of a historical paradox. There are powerful factors supporting the argument that Milan should have become the capital of a unified Italy, and this is the belief of many Milanese, in spite of the fact that the unity of Italy was actually born in Turin, rather than in Milan, in 1870.',
          },
          {
            name: 'Prague just for you ',
            slug: 'prag',
            category: 'city',
            image: '/images/prag.jpg',
            price: 220,
            offer: 'Trip to Pargue of 4 days.' ,
            including: 'Accommodation in famous hotel, Return flight,See the Infant Jesus of Prague, Ticket to  Astronomical Clock Strike an Hour,Stroll across the Charles Bridge,Witness the old Jewish Ghetto',
            description: 'Prague is a 3D architecture textbook. Romanesque chapels and cellars, Gothic cathedrals, Baroque palaces and gardens, worldly Art Nouveau buildings, and unique Cubist architecture make it a place with no parallel in the world. You don’t have to be an expert on individual artistic styles in order to appreciate the diversity of the city’s architecture. The Rotunda of St Martin, the Church of Our Lady before Týn, the Wallenstein Palace and the Municipal House will be forever etched into your memory. Frank Gehry’s Dancing Building has become an icon of modern architecture in Prague, as have new buildings in the Karlín neighbourhood and the new National Technical Library in Dejvice.',
          },
          {
            name: 'Experience Venice',
            slug: 'venice',
            category: 'city',
            image: '/images/venice.jpg',
            price: 180,
            offer: 'Trip to Venice of 3 days.' ,
            including: 'Accommodation in famous hotel, Return flight, Ticket to  St. Mark’s Basilica, Canale Grande,Ponte di Rialto, Gallerie dell’Accademia, Doges Palace',
            description: 'Venice, Italian Venezia, city, major seaport, and capital of both the provincia (province) of Venezia and the regione (region) of Veneto, northern Italy. An island city, it was once the centre of a maritime republic. It was the greatest seaport in late medieval Europe and the continent’s commercial and cultural link to Asia. Venice is unique environmentally, architecturally, and historically, and in its days as a republic the city was styled la serenissima (“the most serene” or “sublime”). It remains a major Italian port in the northern Adriatic Sea and is one of the world’s oldest tourist and cultural centres.',
          },
        
        ],
      
       
};

export default travelData;