const tripData = {
    productsT: [
        {
            name: 'Visit Plitvice Lakes',
            slug: 'plitvice',
            category: 'city',
            image: '/images/plitvice.jpg',
            price: 60,
            offer: 'Trip to Plitvice Lakes.' ,
            including: 'Ticket to Plitvice Lakes, lunch at famous restorant, bus in two ways from Split and Kastela',
            description: 'With its exceptional natural beauty, this area has always attracted nature lovers, and already on 8 April 1949, it was proclaimed Croatia’s first national park. The process of tufa formation, which results in the building of the tufa, or travertine, barriers and resulted in the creation of the lakes, is the outstanding universal value, for which the Plitvice Lakes were internationally recognised on 26 October 1979 with their inscription onto the UNESCO World Heritage List. ',
          },
          {
            name: 'Mostar from Split',
            slug: 'mostar',
            category: 'city',
            image: '/images/mostar.jpg',
            price: 40,
            offer: 'Trip to Mostar.' ,
            including: 'Lunch at famous restorant, bus in two ways from Split and Kastela',
            description: 'Mostar, town, Bosnia and Herzegovina. Mostar is the chief city and, historically, the capital of Herzegovina. It is situated in mountainous country along the Neretva River and lies on the Sarajevo-Ploče rail line. First mentioned in 1452, Mostar became a Turkish garrison town in the 16th century. In 1566 the Turks replaced the town’s wooden suspension bridge over the Neretva with a stone arch one, whence the name Mostar (from Serbo-Croatian most, “bridge”). This stone bridge had a single arch 90 feet (27 metres) wide and was a masterpiece of Ottoman engineering.',
          },
          {
            name: 'Krka',
            slug: 'krka',
            category: 'city',
            image: '/images/krka.jpg',
            price: 540,
            offer: 'Trip to Krka.' ,
            including: 'Lunch at famous restorant, bus in two ways from Split and Kastela',
            description: 'Krka National Park lies about 10km inland from Sibenik in this part of Dalmatia. Named after the Krka River, the Park covers an area of just over 142 square km and includes two thirds of the river itself. The top attraction of the Park are its magnificent waterfalls, including the famous Skradinski Buk falls which are one of Croatia’s most famous sights.Other highlights include the small island of Visovac and Roski Slap waterfall. A boat trip through the park (included in the entrance ticket) is a great way of seeing much of the Park. Best of all, it is possible to swim in some locations in Krka National Park! (To be sure to bring your swimming costume or trunks along!)',
          },
          {
            name: 'Rafting',
            slug: 'rafting',
            category: 'city',
            image: '/images/rafting.jpg',
            price: 35,
            offer: 'Rarfting near Omis' ,
            including: 'Ticket for rafting, lunch at famous restorant, bus in two ways from Split and Kastela',
            description: 'Rafting in Croatia is a wonderful way to experience the unspoiled Croatian mainland. Like most outdoor sports, rafting, in general, has become safer over the years. As a result, the difficulty rating of most river runs has changed. This may be the reason why Croatia is not well known for this particular activity. Although it does have wild and exciting rivers, up to grade 3 that flows through sceneries that will take your breath away. Rafting or white water rafting worldwide is a challenging recreational outdoor activity.',
          },
          {
            name: 'Biokovo',
            slug: 'biokovo',
            category: 'city',
            image: '/images/biokovo.jpg',
            price: 65,
            offer: 'Trip toBiokovo.' ,
            including: 'Ticket to Biokovo, lunch at famous restorant, bus in two ways from Split and Kastela',
            description: 'Public Institution Biokovo Nature Park is currently implementing a project called “New Adrion – Promotion of Sustainable Use of Natural Heritage of Biokovo Nature Park”, funded by the European Regional Development Fund under the Operational Program Competitiveness and Cohesion 2014-2020 with partners Makarska Development Agency MARA and Croatian Mountain Rescue Service - HGSS. The total value of the project is approximately 34 million Kuna, of which the grant amounts to about 27 million Kuna, and the rest is financed by the Fund for Environmental Protection and Energy Efficiency and by own funds collected from users and partners.',
          },
          {
            name: 'Dubrovnik walls',
            slug: 'dubrovnik',
            category: 'city',
            image: '/images/dubrovnik.jpg',
            price: 100,
            offer: 'Trip to Dubrovnik2of 6 days.' ,
            including: 'Bus in two ways from Split and Kastela',
            description: 'The whole Dubrovnik region is well-known for its fascinating landscapes, abundant Mediterranean vegetation, mild climate and interesting smaller settlements. In former times, it became part of the Dubrovnik Republic territory, becoming connected with the city via historical, economic and trade route ties.In tourism, it is now called the Dubrovnik Riviera. Visiting Dubrovnik is not a complete pleasure without seeing at least a part of its surroundings: the good land and sea connections offer the possibility of organizing either shorter or longer excursions.',
          },
          {
            name: 'Mljet',
            slug: 'mljet',
            category: 'city',
            image: '/images/mljet.jpg',
            price: 40,
            offer: 'Trip to Mljet.' ,
            including: 'Ticket to MljetP, lunch at famous restorant, bus in two ways from Split and Kastela',
            description: 'Mljet – the first large island we come upon while sailing the from the southeast in Croatian waters. In historical times, the entire island was inhabited by the Illyrians. The Greeks, on their way to Lumbarda (island of Korčula) and other Adriatic settlements arrived there stayed due to the water and bad weather. The island was also inhabited by the Romans, who left behind archaeological remnants, the most significant of which is the palace in Polače harbor, as well as the names of the island heights, hills and reefs, unquestionable proof of their residence on the island.',
          },
          {
            name: 'Zipline Omis',
            slug: 'zipline',
            category: 'city',
            image: '/images/zipline.jpg',
            price: 80,
            offer: 'Zipline' ,
            including: 'Lunch at famous restorant, bus in two ways from Split and Kastela',
            description: 'Our tours begin at the meeting point at the scheduled tour time. Therefore, we recommend guests to arrive at least 10 minutes prior to the tour time. If you are running late, we will do our best to accommodate you on another tour that same day, given availability.No refunds will be issued to late arrivals – if you fail to show up for your tour on time, we still incur the same costs.',
          },
          {
            name: 'Mosor',
            slug: 'mosor',
            category: 'city',
            image: '/images/mosor.jpg',
            price: 30,
            offer: 'Trip to Mosor.' ,
            including: 'Lunch at famous restorant, bus in two ways from Split and Kastela',
            description: 'Just like all other mountains in the Dinaride range, Mosor stretches northwest-southeast, in parallel with the Adriatic coast, and thanks to its height, it offers spectacular views of open seas and islands. The tops of Mosor neither have vertical cliffs like many Alpine tops, nor do they excel in rich woods like inland mountains. However, they have everything a mountaineering fan needs to be thrilled immediately and then lured to venture into another climb on this mountain.',
          },
        
        ],
      
       
};

export default tripData;